service: preparepte
plugins:
  - serverless-offline
provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 256
  timeout: 30
package:
  patterns:
    - "!/**"
    - "node_modules/@vendia/serverless-express/**"
    - "dist/**"
    - "lambda.js"
functions:
  api:
    handler: lambda.handler
    events:
      - http: GET /
      - http: GET /{proxy+}
